import { Carrier, DataPlan, Language } from './types';

// 1. CARRIER DISPLAY CONFIGURATION
export const CARRIERS = [
  { id: Carrier.MTN, color: 'bg-yellow-400', textColor: 'text-black', logo: 'https://upload.wikimedia.org/wikipedia/commons/9/93/MTN_Logo.svg' },
  { id: Carrier.AIRTEL, color: 'bg-red-600', textColor: 'text-white', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Airtel_logo.svg' },
  { id: Carrier.GLO, color: 'bg-green-600', textColor: 'text-white', logo: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Glo_logo.png' },
  { id: Carrier.NINEMOBILE, color: 'bg-emerald-900', textColor: 'text-white', logo: 'https://upload.wikimedia.org/wikipedia/en/3/30/9mobile_logo.png' }
];

// 2. NETWORK IDS FOR AFFTECH API (Crucial for API calls)
export const NETWORK_IDS: Record<Carrier, string> = {
  [Carrier.MTN]: '1',
  [Carrier.AIRTEL]: '2',
  [Carrier.GLO]: '3',
  [Carrier.NINEMOBILE]: '4'
};

// 3. MOCK DATA PLANS (Fallback if API fails)
export const MOCK_DATA_PLANS: Record<Carrier, DataPlan[]> = {
  [Carrier.MTN]: [
    { id: 'm1', name: 'Daily 100MB', price: 100, validity: '1 Day', allowance: '100MB', category: 'Daily' },
    { id: 'm2', name: 'Weekly 1.5GB', price: 500, validity: '7 Days', allowance: '1.5GB', category: 'Weekly' },
    { id: 'm3', name: 'Monthly 3.5GB', price: 1200, validity: '30 Days', allowance: '3.5GB', category: 'Monthly' },
    { id: 'm4', name: 'Monthly 10GB', price: 3000, validity: '30 Days', allowance: '10GB', category: 'Monthly' },
  ],
  [Carrier.AIRTEL]: [
    { id: 'a1', name: 'Daily 200MB', price: 100, validity: '1 Day', allowance: '200MB', category: 'Daily' },
    { id: 'a2', name: 'Weekly 2GB', price: 500, validity: '7 Days', allowance: '2GB', category: 'Weekly' },
    { id: 'a3', name: 'Monthly 5GB', price: 1500, validity: '30 Days', allowance: '5GB', category: 'Monthly' },
    { id: 'a4', name: 'Monthly 15GB', price: 4000, validity: '30 Days', allowance: '15GB', category: 'Monthly' },
  ],
  [Carrier.GLO]: [
    { id: 'g1', name: 'Mega 1GB', price: 300, validity: '1 Day', allowance: '1GB', category: 'Daily' },
    { id: 'g2', name: 'Weekly 2.5GB', price: 500, validity: '7 Days', allowance: '2.5GB', category: 'Weekly' },
    { id: 'g3', name: 'Monthly 7GB', price: 1500, validity: '30 Days', allowance: '7GB', category: 'Monthly' },
  ],
  [Carrier.NINEMOBILE]: [
    { id: 'n1', name: 'Small 1GB', price: 500, validity: '7 Days', allowance: '1GB', category: 'Weekly' },
    { id: 'n2', name: 'Monthly 2GB', price: 1000, validity: '30 Days', allowance: '2GB', category: 'Monthly' },
  ]
};

// 4. AVAILABLE LANGUAGES
export const LANGUAGES = [
  { id: 'en', name: 'English', flag: '🇳🇬' },
  { id: 'yo', name: 'Yoruba', flag: '🇳🇬' },
  { id: 'ig', name: 'Igbo', flag: '🇳🇬' },
  { id: 'ha', name: 'Hausa', flag: '🇳🇬' },
  { id: 'fr', name: 'French', flag: '🇫🇷' }
];

// 5. TRANSLATIONS
export const TRANSLATIONS: Record<Language | string, Record<string, string>> = {
  en: {
    welcome: 'Welcome Back!',
    create: 'Create Account',
    signin: 'Sign In',
    signup: 'Sign Up',
    buy: 'Buy',
    history: 'Activity',
    assistant: 'Ask AI',
    profile: 'Profile',
    wallet_bal: 'Wallet Balance',
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    select_net: 'Select Network',
    ai_finder: 'AI Plan Finder',
    phone: 'Phone Number',
    airtime: 'Airtime',
    data: 'Data',
    recharge_now: 'Recharge Now',
    lang: 'Language',
    name: 'Full Name',
    email: 'Email Address',
    pass: 'Password',
    done: 'Done! No Cap! 🚀',
    finish: 'Finish',
    confirm: 'Confirm Payment',
    suggested: 'Suggested Plans',
    available: 'Available',
    recent_num: 'Quick Add History',
    use_mine: 'Use Mine',
    auto_renew: 'Auto-renew',
    recurring_confirm: 'Confirm recurring setup?',
    frequency: 'Frequency',
    active_recurring: 'Active Recurring Plans',
    cancel_confirm: 'Are you sure you want to cancel this plan?',
    keep_plan: 'Keep Plan',
    cancel_plan: 'Cancel Plan'
  },
  yo: {
    welcome: 'E kaabo pada!',
    create: 'Ṣẹda Akọọlẹ',
    signin: 'Wọle',
    signup: 'Forukọsilẹ',
    buy: 'Ra',
    history: 'Iṣẹ rẹ',
    assistant: 'Bi AI leere',
    profile: 'Akọọlẹ mi',
    wallet_bal: 'Iwontunwonsi Apamọwọ',
    deposit: 'Fi owo pamọ',
    withdraw: 'Gba owo jade',
    select_net: 'Yan nẹtiwọọki',
    ai_finder: 'AI Olùwá ètò',
    phone: 'Nọmba tẹlifoonu',
    airtime: 'Owo ipe',
    data: 'Data',
    recharge_now: 'Sowo si bayi',
    lang: 'Ede',
    name: 'Orukọ rẹ kikun',
    email: 'Adirẹsi Imeeli',
    pass: 'Ọrọ igbaniwọle',
    done: 'O ti pari! 🚀',
    finish: 'Pari',
    confirm: 'Jẹrisi Isanwo',
    suggested: 'Àwọn ètò tá a dámọ̀ràn',
    available: 'Wà lárọ̀ọ́wọ́tó',
    recent_num: 'Awọn nọmba to kẹhin',
    use_mine: 'Lo temi',
    auto_renew: 'Tuntun laifọwọyi',
    recurring_confirm: 'Jẹrisi eto yii?',
    frequency: 'Iye igba',
    active_recurring: 'Awọn eto ti n ṣiṣẹ',
    cancel_confirm: 'Ṣe o daju pe o fẹ fagilee eto yii?',
    keep_plan: 'Duro eto naa',
    cancel_plan: 'Fagilee eto'
  },
  ig: {
    welcome: 'Nnọọ ọzọ!',
    create: 'Mee Akaụntụ',
    signin: 'Banye',
    signup: 'Debanye aha',
    buy: 'Gote',
    history: 'Ihe Emere',
    assistant: 'Jụọ AI ajụjụ',
    profile: 'Nka m',
    wallet_bal: 'Ego nọ na Wallet',
    deposit: 'Tinye ego',
    withdraw: 'Wepụ ego',
    select_net: 'Họrọ Netwọk',
    ai_finder: 'AI Onye nchọta',
    phone: 'Nọmba ekwentị',
    airtime: 'Ego ekwentị',
    data: 'Data',
    recharge_now: 'Tinye ego ugbu a',
    lang: 'Asụsụ',
    name: 'Aha gị niile',
    email: 'Imeeli',
    pass: 'Paswọọdụ',
    done: 'Emela ya! 🚀',
    finish: 'Mechie',
    confirm: 'Kwenye ego',
    suggested: 'Atụmatụ anyị tụrụ aro',
    available: 'Ọ nọ ebe a',
    recent_num: 'Nọmba ndị mbụ',
    use_mine: 'Nke m',
    auto_renew: 'Tinye ego ọzọ',
    recurring_confirm: 'Ị kwadoro nke a?',
    frequency: 'Ugboro ole',
    active_recurring: 'Atụmatụ na-arụ ọrụ',
    cancel_confirm: 'Ị doro anya na ị chọrọ ịkagbu atụmatụ a?',
    keep_plan: 'Debe atụmatụ',
    cancel_plan: 'Kagbuo atụmatụ'
  },
  ha: {
    welcome: 'Barka da dawowa!',
    create: 'Bude Account',
    signin: 'Shiga',
    signup: 'Rijista',
    buy: 'Saya',
    history: 'Ayyuka',
    assistant: 'Tambayi AI',
    profile: 'Sashina',
    wallet_bal: 'Kudin Wallet',
    deposit: 'Saka kudi',
    withdraw: 'Cire kudi',
    select_net: 'Zabi Network',
    ai_finder: 'AI Mai nemo tsari',
    phone: 'Lambar waya',
    airtime: 'Katin kira',
    data: 'Data',
    recharge_now: 'Saka yanzu',
    lang: 'Yare',
    name: 'Cikakken suna',
    email: 'Email',
    pass: 'Kalmar sirri',
    done: 'An gama! 🚀',
    finish: 'Gama',
    confirm: 'Tabbatar da biya',
    suggested: 'Tsare-tsaren da aka ba da shawara',
    available: 'Akwai',
    recent_num: 'Lambobin kwanan nan',
    use_mine: 'Nawa',
    auto_renew: 'Sake sabuntawa',
    recurring_confirm: 'Tabbatar da wannan tsari?',
    frequency: 'Yawan lokaci',
    active_recurring: 'Tsare-tsaren dake aiki',
    cancel_confirm: 'Shin kun tabbata kuna son soke wannan tsarin?',
    keep_plan: 'Ci gaba da tsarin',
    cancel_plan: 'Soke tsarin'
  },
  fr: {
    welcome: 'Bon retour !',
    create: 'Créer un compte',
    signin: 'Se connecter',
    signup: "S'inscrire",
    buy: 'Acheter',
    history: 'Activité',
    assistant: 'Assistant AI',
    profile: 'Profil',
    wallet_bal: 'Solde du portefeuille',
    deposit: 'Dépôt',
    withdraw: 'Retirer',
    select_net: 'Choisir le réseau',
    ai_finder: 'Recherche de plan AI',
    phone: 'Numéro de téléphone',
    airtime: 'Crédit',
    data: 'Données',
    recharge_now: 'Recharger maintenant',
    lang: 'Langue',
    name: 'Nom complet',
    email: 'Adresse e-mail',
    pass: 'Mot de passe',
    done: 'Terminé ! 🚀',
    finish: 'Terminer',
    confirm: 'Confirmer le paiement',
    suggested: 'Plans suggérés',
    available: 'Disponible',
    recent_num: 'Historique rapide',
    use_mine: 'Utiliser le mien',
    auto_renew: 'Auto-renouveler',
    recurring_confirm: 'Confirmer l\'abonnement?',
    frequency: 'Fréquence',
    active_recurring: 'Abonnements actifs',
    cancel_confirm: 'Êtes-vous sûr de vouloir annuler ce plan?',
    keep_plan: 'Garder le plan',
    cancel_plan: 'Annuler le plan'
  }
};